-- MySQL Script generated by MySQL Workbench
-- Sun Jul  4 14:38:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Empleados
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Empleados` ;

-- -----------------------------------------------------
-- Schema Empleados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Empleados` DEFAULT CHARACTER SET utf8 ;
USE `Empleados` ;

-- -----------------------------------------------------
-- Table `Empleados`.`Tipo_Doc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados`.`Tipo_Doc` ;

CREATE TABLE IF NOT EXISTS `Empleados`.`Tipo_Doc` (
  `Id_Documento` INT NOT NULL,
  `TipoDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleados`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados`.`Estado` ;

CREATE TABLE IF NOT EXISTS `Empleados`.`Estado` (
  `Id_Estado` INT NOT NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empleados`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Empleados`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Empleados`.`Usuarios` (
  `Codigo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Tipo_Docu` INT NOT NULL,
  `Documento` BIGINT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  CONSTRAINT `FK_TIPO_DOC`
    FOREIGN KEY (`Tipo_Docu`)
    REFERENCES `Empleados`.`Tipo_Doc` (`Id_Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ESTADOS`
    FOREIGN KEY (`Estado`)
    REFERENCES `Empleados`.`Estado` (`Id_Estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_TIPO_DOC_idx` ON `Empleados`.`Usuarios` (`Tipo_Docu` ASC) VISIBLE;

CREATE INDEX `FK_ESTADOS_idx` ON `Empleados`.`Usuarios` (`Estado` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Empleados`.`Tipo_Doc`
-- -----------------------------------------------------
START TRANSACTION;
USE `Empleados`;
INSERT INTO `Empleados`.`Tipo_Doc` (`Id_Documento`, `TipoDocumento`) VALUES (1, 'C.C');
INSERT INTO `Empleados`.`Tipo_Doc` (`Id_Documento`, `TipoDocumento`) VALUES (2, 'C.E');
INSERT INTO `Empleados`.`Tipo_Doc` (`Id_Documento`, `TipoDocumento`) VALUES (3, 'PASAPORTE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Empleados`.`Estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `Empleados`;
INSERT INTO `Empleados`.`Estado` (`Id_Estado`, `Estado`) VALUES (1, 'Asistira');
INSERT INTO `Empleados`.`Estado` (`Id_Estado`, `Estado`) VALUES (2, 'Probablemente');
INSERT INTO `Empleados`.`Estado` (`Id_Estado`, `Estado`) VALUES (3, 'No asitire');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Empleados`.`Usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `Empleados`;
INSERT INTO `Empleados`.`Usuarios` (`Codigo`, `Nombre`, `Tipo_Docu`, `Documento`, `Telefono`, `Correo`, `Estado`) VALUES (1, 'Carlos A. Rodriguez Ruiz', 1, 1000590071, '3506910611', 'carlozrr2002@gmail.com', 1);

COMMIT;

